services:
    Symfony\Cmf\Bundle\MediaBundle\Adapter\LiipImagine\CmfMediaDoctrineLoader:
        arguments:
            - '@liip_imagine'
            - '@doctrine_phpcr'
            - '%cmf_media.persistence.phpcr.manager_name%'
            - '@Symfony\Cmf\Bundle\MediaBundle\Doctrine\Phpcr\MediaManager'
            - '%cmf_media.persistence.phpcr.image.class%'

    cmf_media.liip_imagine.doctrine_phpcr.binary.loader:
        alias: Symfony\Cmf\Bundle\MediaBundle\Adapter\LiipImagine\CmfMediaDoctrineLoader
