services:
    Symfony\Cmf\Bundle\MediaBundle\Adapter\ElFinder\PhpcrDriver:
        arguments:
            - '@doctrine_phpcr'
            - '%cmf_media.persistence.phpcr.manager_name%'
            - '@cmf_media.persistence.phpcr.manager'
            - '@cmf_media.templating.helper'
            - '%cmf_media.imagine.filter.elfinder_thumbnail%'
    
    Symfony\Cmf\Bundle\MediaBundle\Editor\Helper\BrowserDefaultHelper:
        arguments:
            - '@router'
            - 'elfinder'
        tags:
            - {name: "cmf_media.browser_file_helper", editor: "default", browser: "elfinder"}

    cmf_media.adapter.elfinder.phpcr_driver:
        alias: '@Symfony\Cmf\Bundle\MediaBundle\Adapter\ElFinder\PhpcrDriver'
    cmd_media.browser_file_helper.default_elfinder:
        alias: 'Symfony\Cmf\Bundle\MediaBundle\Editor\Helper\BrowserDefaultHelper'